/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.border.LineBorder;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Asus
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registrationLabel = new javax.swing.JLabel();
        asteriskUsernameLabel = new javax.swing.JLabel();
        facultyIDLabel = new javax.swing.JLabel();
        facultyIdTextField = new javax.swing.JTextField();
        asteriskNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        asteriskPasswordLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        asteriskRePasswordLabel = new javax.swing.JLabel();
        rePasswordLabel = new javax.swing.JLabel();
        rePasswordField = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        matchLabel = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        errorMessage1 = new javax.swing.JLabel();
        facultyErrorMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        registrationLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registrationLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrationLabel.setText("REGISTRATION FORM");
        jPanel1.add(registrationLabel);
        registrationLabel.setBounds(200, 160, 270, 50);

        asteriskUsernameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        asteriskUsernameLabel.setForeground(new java.awt.Color(255, 0, 0));
        asteriskUsernameLabel.setText("*");
        jPanel1.add(asteriskUsernameLabel);
        asteriskUsernameLabel.setBounds(130, 210, 10, 20);

        facultyIDLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        facultyIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        facultyIDLabel.setText("Faculty ID");
        jPanel1.add(facultyIDLabel);
        facultyIDLabel.setBounds(140, 210, 110, 19);

        facultyIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        facultyIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyIdTextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(facultyIdTextField);
        facultyIdTextField.setBounds(140, 230, 370, 39);

        asteriskNameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        asteriskNameLabel.setForeground(new java.awt.Color(255, 0, 0));
        asteriskNameLabel.setText("*");
        jPanel1.add(asteriskNameLabel);
        asteriskNameLabel.setBounds(130, 300, 10, 20);

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(140, 300, 100, 19);

        lastNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lastNameField);
        lastNameField.setBounds(140, 320, 180, 39);

        lastNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last");
        jPanel1.add(lastNameLabel);
        lastNameLabel.setBounds(140, 360, 80, 19);

        firstNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(firstNameField);
        firstNameField.setBounds(330, 320, 180, 39);

        firstNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First");
        jPanel1.add(firstNameLabel);
        firstNameLabel.setBounds(330, 360, 80, 19);

        asteriskPasswordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        asteriskPasswordLabel.setForeground(new java.awt.Color(255, 0, 0));
        asteriskPasswordLabel.setText("*");
        jPanel1.add(asteriskPasswordLabel);
        asteriskPasswordLabel.setBounds(130, 390, 10, 20);

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(140, 390, 120, 19);

        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(passwordField);
        passwordField.setBounds(140, 410, 374, 39);

        asteriskRePasswordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        asteriskRePasswordLabel.setForeground(new java.awt.Color(255, 0, 0));
        asteriskRePasswordLabel.setText("*");
        jPanel1.add(asteriskRePasswordLabel);
        asteriskRePasswordLabel.setBounds(130, 480, 10, 20);

        rePasswordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rePasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        rePasswordLabel.setText("Re-Password");
        jPanel1.add(rePasswordLabel);
        rePasswordLabel.setBounds(140, 480, 140, 19);

        rePasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(rePasswordField);
        rePasswordField.setBounds(140, 500, 374, 39);

        cancelButton.setText("Back");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);
        cancelButton.setBounds(220, 630, 63, 26);

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton);
        registerButton.setBounds(360, 630, 82, 26);

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\system\\src\\newpackage\\New Logo.png")); // NOI18N
        jPanel1.add(Logo);
        Logo.setBounds(250, 10, 150, 130);

        matchLabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(matchLabel);
        matchLabel.setBounds(230, 600, 50, 0);

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorMessage);
        errorMessage.setBounds(140, 450, 370, 20);

        errorMessage1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorMessage1);
        errorMessage1.setBounds(140, 540, 370, 20);

        facultyErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(facultyErrorMessage);
        facultyErrorMessage.setBounds(140, 270, 370, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("(e.g. FA0000SJ0000)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 210, 190, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\system\\registedBackground.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-40, 0, 690, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:

        LogIn logIn = new LogIn();
        logIn.setVisible(true);
        logIn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
      String facultyID = "";
      String fullName = "";
      String lastName = "";
      String firstName = ""; 
      String password = "";
      
            if(facultyIdTextField.getText().isEmpty() || facultyIdTextField.getText().length() < 11) {
                facultyIdTextField.setBorder(new LineBorder(Color.red));
                facultyErrorMessage.setText("*Please Insert Required Field");
             }else{
                facultyIdTextField.setBorder(new LineBorder(Color.black));
                facultyIdTextField.select(0,2);
                String firstTwoLetters = facultyIdTextField.getSelectedText();
                String selectTwoLetters = firstTwoLetters.toUpperCase();
                facultyIdTextField.select(2, 6);
                String selectFourNumbers = facultyIdTextField.getSelectedText();
                facultyIdTextField.select(6, 8);
                String secondTwoLetters = facultyIdTextField.getSelectedText();
                String secondTwoLettersSelected = secondTwoLetters.toUpperCase();
         
                facultyIdTextField.select(8,12);
                String secondFourNumbers = facultyIdTextField.getSelectedText();
                if(selectTwoLetters.matches("[A-Z]{2,}") &&  selectFourNumbers.matches("[0-9]{4}") && secondTwoLettersSelected.matches("[A-Z]{2,}") && secondFourNumbers.matches("[0-9]{4}")){
                    facultyIdTextField.setBorder(new LineBorder(Color.black));
                    facultyErrorMessage.setText("");
                    try{
                        String sql = "Select Faculty_ID From FacultyData.Registered where Faculty_ID = ?";
                        PreparedStatement statement = conObj.prepareStatement(sql);
                        statement.setString(1,facultyIdTextField.getText());
                        rsObj = statement.executeQuery();
                        if(rsObj.first()){
                           facultyErrorMessage.setText("*Faculty ID Already Exist");
                           facultyIdTextField.setBorder(new LineBorder(Color.red));
                        }else{
                           facultyErrorMessage.setText("");
                           facultyIdTextField.setBorder(new LineBorder(Color.black));
                           facultyID = facultyIdTextField.getText();
                        }
                    }catch(SQLException e){
                        e.printStackTrace();
                    }
                }else{         
                    facultyIdTextField.setBorder(new LineBorder(Color.red));
                    facultyErrorMessage.setText("*Incorrect Format");
                }
             }   
      
        if(lastNameField.getText().equals("")){
            lastNameField.setBorder(new LineBorder(Color.red));
        }else{
            lastNameField.setBorder(new LineBorder(Color.black));
            lastName = lastNameField.getText();
        }
     
        if(firstNameField.getText().equals("")){
            firstNameField.setBorder(new LineBorder(Color.red));
        }else{
            firstNameField.setBorder(new LineBorder(Color.black));
            firstName = firstNameField.getText();     
        }
        
        if(passwordField.getText().equals("")){
            passwordField.setBorder(new LineBorder(Color.red)); 
            errorMessage.setText("*Please Input Your Passowrd");
            rePasswordField.setBorder(new LineBorder(Color.black));
            errorMessage1.setText("");
        }else if(rePasswordField.getText().equals("")){
            rePasswordField.setBorder(new LineBorder(Color.red));
            errorMessage1.setText("*Please Re-Type Passowrd");   
            passwordField.setBorder(new LineBorder(Color.black));
            errorMessage.setText("");
        }else if(!passwordField.getText().equals(rePasswordField.getText())){
            passwordField.setBorder(new LineBorder(Color.red)); 
            errorMessage.setText("*Password Does Not Match");            
            rePasswordField.setBorder(new LineBorder(Color.red));
            errorMessage1.setText("*Re-Typed Password Does Not Match"); 
        }else{ 
            password = passwordField.getText();
            passwordField.setBorder(new LineBorder(Color.black)); 
            errorMessage.setText("");            
            rePasswordField.setBorder(new LineBorder(Color.black));
            errorMessage1.setText("");             
        }
        
        if(!facultyID.equals("") && !lastName.equals("") && !firstName.equals("") && !password.equals("")){           
            if(passwordField.getText().matches(".*[a-z]+.*") && passwordField.getText().matches(".*[0-9].*+") && passwordField.getText().length() > 6){
                fullName = lastName + " " + firstName;
                registerData(facultyID,fullName,password);
                JOptionPane.showMessageDialog(null,"Success");            
                facultyIdTextField.setText("");
                lastNameField.setText("");
                firstNameField.setText("");
                passwordField.setText("");
                rePasswordField.setText("");  
            }else{
                passwordField.setBorder(new LineBorder(Color.red)); 
                errorMessage.setText("*Password does not contain the minumun requirements");
            }
          
        }
        
        
            
    }//GEN-LAST:event_registerButtonActionPerformed

    private void facultyIdTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyIdTextFieldKeyPressed
        // TODO add your handling code here:
      
        String x = facultyIdTextField.getText().toUpperCase();
        
        
    }//GEN-LAST:event_facultyIdTextFieldKeyPressed
    private Connection conObj = null;
    private Statement stateObj = null;
    private ResultSet rsObj = null;
    private String password = "";
    private void connect() {// Creates Connection to the Database
        try{        
        String user = "root";
        String pass = "password";
        conObj = DriverManager.getConnection("jdbc:mysql://localhost:3306/facultydata?useTimezone=true&serverTimezone=UTC", user, pass);
        stateObj = conObj.createStatement(); // Creates a Statement
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        
    }
    private String user = "";

   
    
    
    private void registerData(String user, String name, String password){
        try{
            PreparedStatement prepState = conObj.prepareStatement("INSERT INTO facultydata.registered VALUES (?,?,?)");
            prepState.setString(1,user);
            prepState.setString(2,name);
            prepState.setString(3, password);
            prepState.execute();
        }catch(SQLException e){
           e.printStackTrace();
          
        }
       
    }
    
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel asteriskNameLabel;
    private javax.swing.JLabel asteriskPasswordLabel;
    private javax.swing.JLabel asteriskRePasswordLabel;
    private javax.swing.JLabel asteriskUsernameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel errorMessage1;
    private javax.swing.JLabel facultyErrorMessage;
    private javax.swing.JLabel facultyIDLabel;
    private javax.swing.JTextField facultyIdTextField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel matchLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField rePasswordField;
    private javax.swing.JLabel rePasswordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registrationLabel;
    // End of variables declaration//GEN-END:variables
}
